/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as NeighborhoodsIndexRouteImport } from './routes/neighborhoods.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsIndexRoute = NeighborhoodsIndexRouteImport.update({
  id: '/neighborhoods/',
  path: '/neighborhoods/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/neighborhoods/$slug',
  path: '/neighborhoods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/neighborhoods': typeof NeighborhoodsIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/agents/$id'
    | '/blog/$slug'
    | '/neighborhoods/$slug'
    | '/properties/$id'
    | '/agents/'
    | '/blog/'
    | '/neighborhoods/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/agents/$id'
    | '/blog/$slug'
    | '/neighborhoods/$slug'
    | '/properties/$id'
    | '/agents'
    | '/blog'
    | '/neighborhoods'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/agents/$id'
    | '/blog/$slug'
    | '/neighborhoods/$slug'
    | '/properties/$id'
    | '/agents/'
    | '/blog/'
    | '/neighborhoods/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AgentsIdRoute: typeof AgentsIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NeighborhoodsIndexRoute: typeof NeighborhoodsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/': {
      id: '/neighborhoods/'
      path: '/neighborhoods'
      fullPath: '/neighborhoods/'
      preLoaderRoute: typeof NeighborhoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/neighborhoods/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AgentsIdRoute: AgentsIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  NeighborhoodsSlugRoute: NeighborhoodsSlugRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  NeighborhoodsIndexRoute: NeighborhoodsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
